feat(tokens): Add strategies & a helper module
- token module: utilities
- localStrategy: for verifying username & password
- jwtStrategy: for reading & decoding any incoming JWT

Need to use destructuring from the main index file of models, in order
to have access to all the ORM methods.

fix(tokens): Fix localStrategy config

- No need to override default values when reading POST request
- Destructure User model from the models index, in order to have access
  to the ORM methods that are decorated on to that object.
  - Was getting an error: 'TypeError: User.findOne is not a function'
- Fix params sent to the condition of 'findOne' method
- The ORM returns promises, get the API working with both promises and
  the callbacks expected by the authorization middleware.

fix(passport): Fix jwtStrategy

Combine promise functionality provided by ORM & callback functionality
expected by middleware.